auto: true
permalink: pretty
exclude: ["gitignore", ".rvmrc", ".rbenv-version", "README.md"]
production_url : http://pieter.cc
paginate: 2
markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
