auto: true
permalink: pretty
exclude: ["gitignore", ".rvmrc", ".rbenv-version", "README.md"]
production_url : https://pieter.cc
paginate: 2
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
